# Site settings
title: jinlongwang's blog
header-img: img/home-bg.jpg
email: superrz@126.com
description: "stay simlpe stay foolish"
baseurl: "jinlongwang.github.io"
url: "http://jinlongwang.github.io"
twitter_username: jinlongwang
github_username:  jinlongwang
facebook_username:  jinlongwang

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
